export type Ingredient = { name: string; quantity: number; unit: string }
export type Nutrition = { calories: number; protein: number; carbs: number; fat: number }
export type Recipe = {
  id: string
  name: string
  cuisine: string
  difficulty: "easy" | "medium" | "hard"
  time: number // minutes
  servings: number
  ingredients: Ingredient[]
  steps: string[]
  nutrition: Nutrition
  diet: "none" | "vegetarian" | "vegan" | "gluten-free"
}

const r = (
  id: string,
  name: string,
  cuisine: string,
  difficulty: Recipe["difficulty"],
  time: number,
  servings: number,
  diet: Recipe["diet"],
  ingredients: Ingredient[],
  steps: string[],
  nutrition: Nutrition,
): Recipe => ({
  id,
  name,
  cuisine,
  difficulty,
  time,
  servings,
  ingredients,
  steps,
  nutrition,
  diet,
})

export const RECIPES: Recipe[] = [
  r(
    "r1",
    "Tomato Basil Pasta",
    "italian",
    "easy",
    25,
    2,
    "vegetarian",
    [
      { name: "pasta", quantity: 200, unit: "g" },
      { name: "tomato", quantity: 3, unit: "pcs" },
      { name: "garlic", quantity: 2, unit: "cloves" },
      { name: "olive oil", quantity: 2, unit: "tbsp" },
      { name: "basil", quantity: 10, unit: "leaves" },
    ],
    ["Boil pasta", "Saute garlic", "Add tomatoes", "Toss pasta with sauce", "Finish with basil"],
    { calories: 500, protein: 15, carbs: 80, fat: 12 },
  ),
  r(
    "r2",
    "Chicken Stir-Fry",
    "chinese",
    "medium",
    30,
    2,
    "none",
    [
      { name: "chicken", quantity: 300, unit: "g" },
      { name: "bell pepper", quantity: 1, unit: "pc" },
      { name: "onion", quantity: 1, unit: "pc" },
      { name: "soy sauce", quantity: 2, unit: "tbsp" },
      { name: "garlic", quantity: 2, unit: "cloves" },
    ],
    ["Slice chicken and veg", "Stir-fry chicken", "Add vegetables", "Add sauce", "Serve with rice"],
    { calories: 620, protein: 45, carbs: 50, fat: 20 },
  ),
  r(
    "r3",
    "Veggie Fried Rice",
    "asian",
    "easy",
    20,
    2,
    "vegetarian",
    [
      { name: "rice", quantity: 300, unit: "g" },
      { name: "egg", quantity: 2, unit: "pcs" },
      { name: "carrot", quantity: 1, unit: "pc" },
      { name: "peas", quantity: 100, unit: "g" },
      { name: "soy sauce", quantity: 1, unit: "tbsp" },
    ],
    ["Scramble eggs", "Stir-fry veggies", "Add rice", "Season", "Serve"],
    { calories: 540, protein: 17, carbs: 90, fat: 12 },
  ),
  r(
    "r4",
    "Beef Tacos",
    "mexican",
    "easy",
    25,
    3,
    "none",
    [
      { name: "beef", quantity: 300, unit: "g" },
      { name: "taco shells", quantity: 6, unit: "pcs" },
      { name: "onion", quantity: 1, unit: "pc" },
      { name: "tomato", quantity: 1, unit: "pc" },
      { name: "cheese", quantity: 60, unit: "g" },
    ],
    ["Cook beef", "Warm shells", "Top with veg and cheese", "Assemble", "Serve"],
    { calories: 700, protein: 35, carbs: 60, fat: 30 },
  ),
  r(
    "r5",
    "Mushroom Risotto",
    "italian",
    "medium",
    40,
    2,
    "vegetarian",
    [
      { name: "rice", quantity: 200, unit: "g" },
      { name: "mushroom", quantity: 200, unit: "g" },
      { name: "onion", quantity: 1, unit: "pc" },
      { name: "butter", quantity: 1, unit: "tbsp" },
      { name: "stock", quantity: 600, unit: "ml" },
    ],
    ["Saute onion", "Add rice", "Add stock gradually", "Stir in mushrooms and butter", "Serve creamy"],
    { calories: 580, protein: 12, carbs: 88, fat: 16 },
  ),
  r(
    "r6",
    "Grilled Lemon Chicken",
    "mediterranean",
    "easy",
    35,
    2,
    "none",
    [
      { name: "chicken", quantity: 300, unit: "g" },
      { name: "lemon", quantity: 1, unit: "pc" },
      { name: "olive oil", quantity: 1, unit: "tbsp" },
      { name: "garlic", quantity: 2, unit: "cloves" },
      { name: "oregano", quantity: 1, unit: "tsp" },
    ],
    ["Marinate", "Grill chicken", "Rest", "Squeeze lemon", "Serve"],
    { calories: 520, protein: 45, carbs: 5, fat: 30 },
  ),
  r(
    "r7",
    "Vegan Buddha Bowl",
    "fusion",
    "easy",
    25,
    2,
    "vegan",
    [
      { name: "quinoa", quantity: 150, unit: "g" },
      { name: "chickpeas", quantity: 200, unit: "g" },
      { name: "spinach", quantity: 100, unit: "g" },
      { name: "carrot", quantity: 1, unit: "pc" },
      { name: "lemon", quantity: 1, unit: "pc" },
    ],
    ["Cook quinoa", "Roast chickpeas", "Assemble bowl", "Dress with lemon", "Serve"],
    { calories: 480, protein: 18, carbs: 72, fat: 10 },
  ),
  r(
    "r8",
    "Gluten-Free Pancakes",
    "american",
    "easy",
    20,
    2,
    "gluten-free",
    [
      { name: "gluten-free flour", quantity: 150, unit: "g" },
      { name: "milk", quantity: 240, unit: "ml" },
      { name: "egg", quantity: 1, unit: "pc" },
      { name: "butter", quantity: 1, unit: "tbsp" },
      { name: "sugar", quantity: 1, unit: "tbsp" },
    ],
    ["Make batter", "Cook on griddle", "Flip", "Serve with butter", "Enjoy"],
    { calories: 520, protein: 12, carbs: 80, fat: 16 },
  ),
  r(
    "r9",
    "Shakshuka",
    "middle eastern",
    "medium",
    30,
    2,
    "vegetarian",
    [
      { name: "egg", quantity: 4, unit: "pcs" },
      { name: "tomato", quantity: 4, unit: "pcs" },
      { name: "onion", quantity: 1, unit: "pc" },
      { name: "garlic", quantity: 2, unit: "cloves" },
      { name: "bell pepper", quantity: 1, unit: "pc" },
    ],
    ["Saute aromatics", "Add tomatoes", "Simmer", "Poach eggs", "Serve"],
    { calories: 420, protein: 22, carbs: 28, fat: 22 },
  ),
  r(
    "r10",
    "Beef and Broccoli",
    "asian",
    "medium",
    25,
    2,
    "none",
    [
      { name: "beef", quantity: 250, unit: "g" },
      { name: "broccoli", quantity: 200, unit: "g" },
      { name: "garlic", quantity: 2, unit: "cloves" },
      { name: "soy sauce", quantity: 2, unit: "tbsp" },
      { name: "cornstarch", quantity: 1, unit: "tsp" },
    ],
    ["Marinate beef", "Stir-fry", "Add broccoli", "Sauce and simmer", "Serve with rice"],
    { calories: 580, protein: 38, carbs: 35, fat: 28 },
  ),
  r(
    "r11",
    "Garlic Butter Shrimp",
    "seafood",
    "easy",
    15,
    2,
    "none",
    [
      { name: "shrimp", quantity: 300, unit: "g" },
      { name: "garlic", quantity: 3, unit: "cloves" },
      { name: "butter", quantity: 2, unit: "tbsp" },
      { name: "lemon", quantity: 1, unit: "pc" },
      { name: "parsley", quantity: 1, unit: "tbsp" },
    ],
    ["Saute garlic", "Add shrimp", "Butter and lemon", "Garnish", "Serve"],
    { calories: 430, protein: 35, carbs: 6, fat: 28 },
  ),
  r(
    "r12",
    "Spinach Omelette",
    "breakfast",
    "easy",
    10,
    1,
    "vegetarian",
    [
      { name: "egg", quantity: 2, unit: "pcs" },
      { name: "spinach", quantity: 50, unit: "g" },
      { name: "cheese", quantity: 20, unit: "g" },
      { name: "butter", quantity: 1, unit: "tsp" },
      { name: "onion", quantity: 0.25, unit: "pc" },
    ],
    ["Whisk eggs", "Cook filling", "Add eggs", "Fold", "Serve"],
    { calories: 300, protein: 20, carbs: 4, fat: 22 },
  ),
  r(
    "r13",
    "Lentil Soup",
    "mediterranean",
    "easy",
    40,
    4,
    "vegan",
    [
      { name: "lentils", quantity: 250, unit: "g" },
      { name: "carrot", quantity: 2, unit: "pcs" },
      { name: "onion", quantity: 1, unit: "pc" },
      { name: "garlic", quantity: 2, unit: "cloves" },
      { name: "stock", quantity: 800, unit: "ml" },
    ],
    ["Saute aromatics", "Add lentils and stock", "Simmer", "Blend partially", "Serve"],
    { calories: 420, protein: 24, carbs: 60, fat: 6 },
  ),
  r(
    "r14",
    "Greek Salad",
    "greek",
    "easy",
    15,
    2,
    "vegetarian",
    [
      { name: "tomato", quantity: 2, unit: "pcs" },
      { name: "cucumber", quantity: 1, unit: "pc" },
      { name: "onion", quantity: 0.5, unit: "pc" },
      { name: "feta", quantity: 80, unit: "g" },
      { name: "olive oil", quantity: 2, unit: "tbsp" },
    ],
    ["Chop veg", "Crumble feta", "Dress", "Toss", "Serve"],
    { calories: 350, protein: 10, carbs: 18, fat: 26 },
  ),
  r(
    "r15",
    "Tofu Stir-Fry",
    "asian",
    "medium",
    25,
    2,
    "vegan",
    [
      { name: "tofu", quantity: 250, unit: "g" },
      { name: "broccoli", quantity: 150, unit: "g" },
      { name: "bell pepper", quantity: 1, unit: "pc" },
      { name: "soy sauce", quantity: 2, unit: "tbsp" },
      { name: "garlic", quantity: 2, unit: "cloves" },
    ],
    ["Press tofu", "Stir-fry tofu", "Add veg", "Add sauce", "Serve"],
    { calories: 480, protein: 26, carbs: 30, fat: 22 },
  ),
  r(
    "r16",
    "Baked Salmon",
    "seafood",
    "easy",
    20,
    2,
    "none",
    [
      { name: "salmon", quantity: 300, unit: "g" },
      { name: "lemon", quantity: 1, unit: "pc" },
      { name: "olive oil", quantity: 1, unit: "tbsp" },
      { name: "garlic", quantity: 2, unit: "cloves" },
      { name: "dill", quantity: 1, unit: "tsp" },
    ],
    ["Season salmon", "Bake", "Rest", "Finish with lemon", "Serve"],
    { calories: 520, protein: 38, carbs: 0, fat: 38 },
  ),
  r(
    "r17",
    "Chickpea Curry",
    "indian",
    "medium",
    30,
    3,
    "vegan",
    [
      { name: "chickpeas", quantity: 400, unit: "g" },
      { name: "tomato", quantity: 2, unit: "pcs" },
      { name: "onion", quantity: 1, unit: "pc" },
      { name: "garlic", quantity: 2, unit: "cloves" },
      { name: "curry powder", quantity: 2, unit: "tsp" },
    ],
    ["Saute onions", "Add spices", "Add tomato and chickpeas", "Simmer", "Serve with rice"],
    { calories: 560, protein: 20, carbs: 80, fat: 14 },
  ),
  r(
    "r18",
    "Cauliflower Rice Bowl",
    "fusion",
    "easy",
    20,
    2,
    "vegan",
    [
      { name: "cauliflower", quantity: 300, unit: "g" },
      { name: "spinach", quantity: 100, unit: "g" },
      { name: "lemon", quantity: 1, unit: "pc" },
      { name: "olive oil", quantity: 1, unit: "tbsp" },
      { name: "garlic", quantity: 1, unit: "clove" },
    ],
    ["Pulse cauliflower", "Saute", "Add veg", "Season", "Serve"],
    { calories: 280, protein: 10, carbs: 20, fat: 14 },
  ),
  r(
    "r19",
    "Gluten-Free Pesto Pasta",
    "italian",
    "easy",
    20,
    2,
    "gluten-free",
    [
      { name: "gluten-free pasta", quantity: 200, unit: "g" },
      { name: "basil", quantity: 20, unit: "g" },
      { name: "olive oil", quantity: 2, unit: "tbsp" },
      { name: "garlic", quantity: 1, unit: "clove" },
      { name: "parmesan", quantity: 30, unit: "g" },
    ],
    ["Cook pasta", "Blend pesto", "Toss", "Serve", "Enjoy"],
    { calories: 540, protein: 14, carbs: 78, fat: 18 },
  ),
  r(
    "r20",
    "Stuffed Bell Peppers",
    "mexican",
    "hard",
    60,
    3,
    "none",
    [
      { name: "bell pepper", quantity: 3, unit: "pcs" },
      { name: "rice", quantity: 200, unit: "g" },
      { name: "beef", quantity: 200, unit: "g" },
      { name: "onion", quantity: 1, unit: "pc" },
      { name: "tomato", quantity: 1, unit: "pc" },
    ],
    ["Par-cook peppers", "Prepare filling", "Stuff", "Bake", "Serve"],
    { calories: 620, protein: 28, carbs: 70, fat: 22 },
  ),
]
